# these messages should be fairly obvious as to their purpose
messages:
  guard:
    on-duty:
      on-duty: '&6You are now on duty!'
      already: '&4You are already on duty!'
      permission: '&4You must be a guard to go on duty.'
      announcement: '&4&l[&6&lPA&4&l] &b&l%s&b is now &lon&b duty.'
      ready-up: '&6Do not forget to ready up by wearing your armor!' 
    off-duty:
      off-duty: '&6You are now off duty!'
      already: '&4You are already off duty!'
      permission: '&4You must be a guard to go off duty.'
      announcement: '&4&l[&6&lPA&4&l] &b&l%s&b is now &loff&b duty.'
      removed-armor: '&6Your armor has been &lremoved&6 and put in your inventory.'
    payroll: '&aYou were paid &l%s&a for your service, thank you!'
    drops-disposed: '&4Your inventory was collected by your supervisor and bagged for evidence.'
    drop-disposed: '&6You have confiscated (and destroyed): &4&l%s&6.'
  guards:
    on-duty:
      any: '&6Guards on duty [&4&l%d&6]:&r %s'
      none: '&4There are &lno&4 guards on duty.'
    off-duty:
      any: '&6Guards off duty [&4&l%d&6]:&r %s'
      none: '&4There are &lno&4 guards off duty.'
    permission: '&4You do not have permission to access that command.'
  enabled: '&aGuard duty enabled, remember to go &lon-duty&a to get paid!'
  reload:
    permission: '&4You do not have permission to access that command.'
    complete: '&aGuardDuty configuration reloaded!'
  announcements:
    kos-active: '&4&l[&6&lPA&4&l] &bAttention everyone, contraband is &4&lKOS&b.'
    kos-inactive: '&4&l[&6&lPA&4&l] &bAttention everyone, contraband is &a&lNOT KOS&b.'

# the threshold determines which associated message, if any, is displayed
thresholds:
  # checked using guardsOnDuty > announcement
  announcement: 0
  # checked using guardsOnDuty < kos
  kos: 3

# these schedule values are in seconds
schedules:
  salaries: 600
  announcements: 480
  
# give the appropriate permission to grant the guard the associated salary per interval
# simply give your guards permissions similar to 'guardduty.salary.cguard'
# list salaries in descending rank order to ensure proper salaries are dispersed
salaries:
  srwarden: 800
  warden: 400
  srguard: 250
  aguard: 150
  bguard: 100
  cguard: 50

# whether or not to announce guards going on/off duty
announce:
  on-duty: true
  off-duty: true

# inventory control options to keep your guards from profiting off of pvp
inventory:
  # automatically disposes all drops when guards pick them up
  auto-dispose: true
  # disallow drops from on-duty guards
  prevent-drops: true
  # forcibly remove the guards armor when going off duty
  remove-off-duty: true
  # do guards drop items on death
  drop-on-death: false

# list of items allowed to be picked up by guards
# useful to allow guards to pickup saplings for re-planting
allowed-pickups:
  - 6

# list of items allowed to be dropped by guards
# useful to allow guards to give saplings for re-planting
allowed-drops:
  - 6

# announce to the guard if the following items are picked up
# damage value is ignored, only ID is considered
# do not use quotes in this section
notify-pickups:
  - 261
  - 262
  - 267
  - 268
  - 272
  - 276
  - 283