name: GuardDuty
author: MortuTBK
description: Manage and pay your guards!
website: http://ci.mortu.net/job/GuardDuty/
main: net.mortu.guardduty.GuardDuty
version: 1.0
softdepend: [Vault]
commands:
  guard:
    description: Gets/sets your guard status as on duty.
    usage: |
      /guard <on|off>
      Example: /guard on - go on duty as a guard
      Example: /guard off - go off duty as a guard
    permissions: guardduty.guard
    permission-message: You must be a guard to go on/off duty.
    aliases: gd
  guards:
    description: Lists the guards on duty.
    usage: /guards
    permissions: gaurdduty.gaurds
    permission-message: You do not have access to that command.
    aliases: gds
permissions:
  guardduty.*:
    description: Gives access to all guard duty commands.
    children:
      guardduty.guard: true
      guardduty.gaurds: true
      guardduty.reload: true
  guardduty.guard:
    description: Allows you to go on/off duty.
  guardduty.guards:
    description: Allows you to see the guards on duty.
  guardduty.reload:
    description: Allows you to reload the guard duty config.
